spring:
  application:
    name: devflow-api
  datasource:
    url: jdbc:mysql://192.168.15.100:3306/devflow?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: shice2022mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: false
  rabbitmq:
    host: 192.168.15.100
    port: 5672
    username: root
    password: 123456
    virtual-host: /
  data:
    redis:
      host: 192.168.15.100
      port: 6379
      database: 15
      timeout: 2000ms

server:
  port: 8080

devflow:
  security:
    jwt:
      issuer: devflow-api
      secret: devflow-phase1-super-secret-key-please-change-in-prod-2026
      access-token-minutes: 15
      refresh-token-days: 30
  bootstrap:
    admin:
      enabled: true
      username: admin
      password: Admin@123456
      display-name: DevFlow Admin
  cache:
    redis:
      enabled: true
  storage:
    minio:
      enabled: true
      endpoint: http://192.168.15.100:9000
      access-key: devflow
      secret-key: devflow123
      bucket: devflow-public
      public-base-url: http://192.168.15.100:9000/devflow-public
      avatar-prefix: avatars
      post-cover-prefix: post-covers
      max-file-size-bytes: 5242880
